const {z}=require('zod');
const https=z.string().url().refine(s=>new URL(s).protocol==='https:','HTTPS required');
const identity=z.object({player:z.string().trim().min(1).max(100),year:z.number().int().min(1800).max(2100),set:z.string().trim().min(1).max(200),number:z.string().trim().min(1).max(60),version:z.string().trim().min(1).max(150)}).strict();
const sale=z.object({marketplace:z.enum(['eBay','Fanatics','Other']),grader:z.enum(['Raw','PSA','CGC']),grade:z.enum(['Raw','9','10','Pristine 10']),price:z.number().positive().max(10000000),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s&&s<=new Date().toISOString().slice(0,10),'Valid nonfuture date required'),url:https,title:z.string().min(1).max(1000),evidence:z.enum(['direct_completed_sale','aggregator_reported']),label_confirmed:z.boolean().default(false),currency:z.literal('USD').default('USD')}).strict().refine(s=>(s.grader==='Raw')===(s.grade==='Raw')&&(s.grade!=='Pristine 10'||s.grader==='CGC'),'Grader and grade mismatch');
const record=z.object({card:identity,checked_at:z.string().datetime(),population:z.object({psa9:z.number().int().nonnegative().nullable(),psa10:z.number().int().nonnegative().nullable(),source_url:https.nullable(),as_of:z.string().max(100).nullable(),basis:z.enum(['official_exact','aggregator_grouped','unavailable'])}).strict(),sales:z.array(sale).max(100),notes:z.array(z.string().max(2000)).max(20).default([])}).strict().superRefine((r,ctx)=>{if(r.population.basis==='unavailable'&&(r.population.psa9!==null||r.population.psa10!==null))ctx.addIssue({code:'custom',message:'Unavailable population must be null'});if(r.population.basis!=='unavailable'&&!r.population.source_url)ctx.addIssue({code:'custom',message:'Population source required'});const seen=new Set();for(const s of r.sales){if(seen.has(s.url))ctx.addIssue({code:'custom',message:'Duplicate sale URL'});seen.add(s.url);}if(Date.parse(r.checked_at)>Date.now()+60000)ctx.addIssue({code:'custom',message:'Future research date'});});
const key=c=>[c.player,c.year,c.set,c.number,c.version].map(x=>String(x).trim().toLowerCase()).join('|');
function analyze(r){const groups={};const cutoff=new Date(Date.now()-180*86400000).toISOString().slice(0,10);for(const platform of ['eBay','Fanatics','Other'])for(const g of ['Raw','PSA 9','PSA 10','CGC 9','CGC 10','CGC Pristine 10']){const rows=r.sales.filter(s=>s.marketplace===platform&&(s.grader==='Raw'?'Raw':s.grader+' '+s.grade)===g&&(g!=='CGC 10'||s.label_confirmed)).sort((a,b)=>b.date.localeCompare(a.date)||a.url.localeCompare(b.url));const recent=rows.filter(s=>s.date>=cutoff).slice(0,5);groups[platform+'|'+g]={count:recent.length,available_count:rows.length,average:recent.length?Math.round(recent.reduce((a,s)=>a+s.price,0)/recent.length*100)/100:null,oldest:recent.at(-1)?.date||null,newest:recent[0]?.date||null,records:recent};}
const p=r.population,total=p.psa9!==null&&p.psa10!==null?p.psa9+p.psa10:null;const raw=groups['eBay|Raw'].average??groups['Fanatics|Raw'].average;const c9=groups['eBay|CGC 9'].average??groups['Fanatics|CGC 9'].average,c10=groups['eBay|CGC 10'].average??groups['Fanatics|CGC 10'].average;
let status='partial';if(total!==null&&total<50)status='excluded_low_population';else if(total!==null&&p.psa10<=p.psa9)status='excluded_grade_distribution';else if(total>=50&&p.psa10>p.psa9&&raw!==null&&c10!==null)status=c10*.85-raw-11>0?'candidate':'excluded_unprofitable';return {groups,raw_price:raw,population_combined:total,ten_share_among9and10:total?p.psa10/total:null,status,has_cgc9:c9!==null,needs_manual_check:true,screening_fee_assumption:0.15,unconfirmed_cgc10_count:r.sales.filter(s=>s.grader==='CGC'&&s.grade==='10'&&!s.label_confirmed).length};}
module.exports={identity,sale,record,key,analyze};
