const crypto=require('node:crypto');
const {McpServer}=require('@modelcontextprotocol/sdk/server/mcp.js');
const {StreamableHTTPServerTransport}=require('@modelcontextprotocol/sdk/server/streamableHttp.js');
const {z}=require('zod');
const {record,key,analyze}=require('./research-model');
const ORIGIN='https://pokemon-grade-flips-production.up.railway.app';
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const random=()=>crypto.randomBytes(32).toString('base64url');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
function html(res,text){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'"});res.end(text);}
async function body(req){let s='';for await(const c of req){s+=c;if(Buffer.byteLength(s)>300000)throw Error('Body too large');}return req.headers['content-type']?.includes('application/x-www-form-urlencoded')?Object.fromEntries(new URLSearchParams(s)):JSON.parse(s||'{}');}
const strategy={purpose:'Research candidates here using available research tools; this plugin stores evidence and does not scrape or provide web search.',batch_size:5,grading_cost:11,minimum_combined_psa9and10:50,prefer_more_psa10_than9:true,rules:['Exact year, set, number and version; never mix variants.','Separate eBay and Fanatics, and PSA/CGC/Pristine.','Only completed sales; generic Grade 9 guide values are not grader-specific.','Keep unsupported prices/populations null; record sources and dates.','Use up to five newest available sales within 180 days; label aggregator evidence.','Confirm CGC Gem Mint label before using CGC 10 in averages.','Historical 10-versus-9 ratio is not raw grading probability.','MANDATORY: Search exact-card PSA 10 and PSA 9 completed sales and PSA 10/9 populations BEFORE selecting a card. A raw price below budget is not a recommendation.','For a shortlist require at least 50 combined PSA9+10, more10 than9, raw sales and PSA10 sales. Missing CGC data means only half the market is known.','Do not fill a five-card batch with raw-only cards. Research more cards or return fewer qualifying cards. Save raw-only findings only as incomplete evidence.','Attach an exact-card HTTPS image_url when a trustworthy matching image is available; never substitute another variant.','Include direct completed-sale links for each grade whenever accessible.','Save researched records, then give a short summary and dashboard link.','Do not promise unattended overnight scans.']};
function createPlugin(pool){
let ready=false;const attempts=new Map();
async function init(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS gradeflip_research (card_key TEXT PRIMARY KEY, data JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS gradeflip_research_batches (batch_id TEXT PRIMARY KEY, payload_hash TEXT NOT NULL, card_keys JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS gradeflip_oauth_clients (id TEXT PRIMARY KEY, redirects JSONB NOT NULL); CREATE TABLE IF NOT EXISTS gradeflip_oauth_codes (code_hash TEXT PRIMARY KEY, data JSONB NOT NULL, expires TIMESTAMPTZ NOT NULL); CREATE TABLE IF NOT EXISTS gradeflip_oauth_tokens (token_hash TEXT PRIMARY KEY, expires TIMESTAMPTZ NOT NULL);`);ready=true;}
function passwordOK(value){const secret=process.env.GRADEFLIP_PLUGIN_PASSWORD;return secret&&crypto.timingSafeEqual(Buffer.from(hash(String(value||''))),Buffer.from(hash(secret)));}
function limited(req){const ip=(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0];const now=Date.now(),old=attempts.get(ip);const a=old&&old.start>now-60000?old:{start:now,n:0};a.n++;attempts.set(ip,a);if(attempts.size>1000)attempts.clear();return a.n>15;}
async function token(){const t=random();await pool.query('INSERT INTO gradeflip_oauth_tokens(token_hash,expires) VALUES($1,NOW()+INTERVAL \'30 days\')',[hash(t)]);return t;}
async function authorized(req){const bearer=req.headers.authorization?.replace(/^Bearer /,'');const cookie=req.headers.cookie?.match(/(?:^|; )gradeflip_research=([^;]+)/)?.[1];const t=bearer||cookie;if(!t||!ready)return false;return Boolean((await pool.query('SELECT 1 FROM gradeflip_oauth_tokens WHERE token_hash=$1 AND expires>NOW()',[hash(t)])).rowCount);}
async function save(args){const parsed=z.object({batch_id:z.string().min(1).max(100),cards:z.array(record).min(1).max(5)}).strict().parse(args);const keys=parsed.cards.map(r=>key(r.card));if(new Set(keys).size!==keys.length)throw Error('Duplicate card in batch');const payload=hash(JSON.stringify(parsed.cards));const db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(hashtext($1))',[parsed.batch_id]);const old=await db.query('SELECT * FROM gradeflip_research_batches WHERE batch_id=$1',[parsed.batch_id]);if(old.rowCount){if(old.rows[0].payload_hash!==payload)throw Error('Batch ID already used with different data');await db.query('COMMIT');return {saved:keys.length,idempotent:true,keys};}for(const r of parsed.cards)await db.query('INSERT INTO gradeflip_research(card_key,data) VALUES($1,$2) ON CONFLICT(card_key) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW() WHERE (gradeflip_research.data->>\'checked_at\')::timestamptz <= (EXCLUDED.data->>\'checked_at\')::timestamptz',[key(r.card),r]);await db.query('INSERT INTO gradeflip_research_batches(batch_id,payload_hash,card_keys) VALUES($1,$2,$3)',[parsed.batch_id,payload,JSON.stringify(keys)]);await db.query('COMMIT');return {saved:keys.length,idempotent:false,keys,dashboard_url:ORIGIN+'/research'};}catch(e){await db.query('ROLLBACK');throw e;}finally{db.release();}}
async function list(args={}){args=z.object({player:z.string().optional(),status:z.enum(['candidate','partial','excluded_low_population','excluded_grade_distribution','excluded_unprofitable']).optional(),raw_min:z.coerce.number().nonnegative().optional(),raw_max:z.coerce.number().nonnegative().optional(),offset:z.coerce.number().int().min(0).default(0),limit:z.coerce.number().int().min(1).max(100).default(50)}).parse(args);const rows=await pool.query('SELECT card_key,data FROM gradeflip_research ORDER BY updated_at DESC LIMIT 2000');let items=rows.rows.map(r=>({key:r.card_key,...r.data,analysis:analyze(r.data)}));if(args.player)items=items.filter(r=>r.card.player.toLowerCase().includes(args.player.toLowerCase()));if(args.status)items=items.filter(r=>r.analysis.status===args.status);if(args.raw_min!=null)items=items.filter(r=>r.analysis.raw_price!==null&&r.analysis.raw_price>=args.raw_min);if(args.raw_max!=null)items=items.filter(r=>r.analysis.raw_price!==null&&r.analysis.raw_price<args.raw_max);return {total:items.length,cards:items.slice(args.offset||0,(args.offset||0)+(args.limit||50)),dashboard_url:ORIGIN+'/research'};}
function mcp(){const s=new McpServer({name:'gradeflip-research',version:'1.0.0'});const meta={securitySchemes:[{type:'oauth2',scopes:['research:read','research:write']}]};const reply=data=>({content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data});s.registerTool('research_strategy',{description:'Read the card-screening strategy before researching. Does not fetch external data.',inputSchema:{},annotations:{readOnlyHint:true,openWorldHint:false},_meta:meta},async()=>reply(strategy));s.registerTool('save_research_batch',{description:'Save up to five exact-card research records with sale and population evidence. Never invent missing data. Preserves existing Pokemon prices.',inputSchema:{batch_id:z.string().min(1).max(100),cards:z.array(record).min(1).max(5)},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},_meta:meta},async args=>reply(await save(args)));s.registerTool('list_researched_cards',{description:'Find saved card research by player, evidence status or raw price range. raw_max is exclusive.',inputSchema:{player:z.string().optional(),status:z.enum(['candidate','partial','excluded_low_population','excluded_grade_distribution','excluded_unprofitable']).optional(),raw_min:z.number().nonnegative().optional(),raw_max:z.number().nonnegative().optional(),offset:z.number().int().nonnegative().default(0),limit:z.number().int().min(1).max(100).default(50)},annotations:{readOnlyHint:true,openWorldHint:false},_meta:meta},async args=>reply(await list(args)));s.registerTool('get_researched_card',{description:'Retrieve full sale evidence for an exact saved card key.',inputSchema:{card_key:z.string().min(1).max(1000)},annotations:{readOnlyHint:true,openWorldHint:false},_meta:meta},async({card_key})=>{const r=await pool.query('SELECT data FROM gradeflip_research WHERE card_key=$1',[card_key]);return reply(r.rowCount?{card:r.rows[0].data,analysis:analyze(r.rows[0].data)}:{found:false});});return s;}
async function route(req,res){const u=new URL(req.url,ORIGIN),p=u.pathname;if(!['/mcp','/plugin/login','/plugin/register','/plugin/authorize','/plugin/token','/api/research','/api/research-health','/.well-known/oauth-protected-resource','/.well-known/oauth-protected-resource/mcp','/.well-known/oauth-authorization-server'].includes(p))return false;
if(p==='/api/research-health'){json(res,200,{ready,auth_configured:Boolean(process.env.GRADEFLIP_PLUGIN_PASSWORD),version:'1.0.0'});return true;}
if(p.startsWith('/.well-known/oauth-protected-resource')){json(res,200,{resource:ORIGIN+'/mcp',authorization_servers:[ORIGIN],scopes_supported:['research:read','research:write']});return true;}
if(p==='/.well-known/oauth-authorization-server'){json(res,200,{issuer:ORIGIN,authorization_endpoint:ORIGIN+'/plugin/authorize',token_endpoint:ORIGIN+'/plugin/token',registration_endpoint:ORIGIN+'/plugin/register',response_types_supported:['code'],grant_types_supported:['authorization_code'],token_endpoint_auth_methods_supported:['none'],code_challenge_methods_supported:['S256'],scopes_supported:['research:read','research:write'],authorization_response_iss_parameter_supported:true});return true;}
if(!ready||!process.env.GRADEFLIP_PLUGIN_PASSWORD){json(res,503,{error:'Plugin database or sign-in configuration unavailable'});return true;}
if(p==='/plugin/register'&&req.method==='POST'){if(limited(req)){json(res,429,{error:'Try again later'});return true;}const b=await body(req);if(!Array.isArray(b.redirect_uris)||!b.redirect_uris.length||b.redirect_uris.length>5||b.redirect_uris.some(s=>{try{const x=new URL(s);return x.protocol!=='https:'||!['chatgpt.com','chat.openai.com'].includes(x.hostname)||x.hash;}catch{return true;}})){json(res,400,{error:'ChatGPT HTTPS redirects required'});return true;}const id=random();await pool.query('INSERT INTO gradeflip_oauth_clients(id,redirects) VALUES($1,$2)',[id,JSON.stringify(b.redirect_uris)]);json(res,201,{client_id:id,redirect_uris:b.redirect_uris,token_endpoint_auth_method:'none',grant_types:['authorization_code'],response_types:['code']});return true;}
if(p==='/plugin/authorize'){if(!['GET','POST'].includes(req.method)){json(res,405,{error:'Method not allowed'});return true;}let q=Object.fromEntries(u.searchParams);if(req.method==='POST'){const b=await body(req);if(limited(req)||!passwordOK(b.password)){json(res,401,{error:'Incorrect connection password or too many attempts'});return true;}q=Object.fromEntries(new URLSearchParams(b.request));const expiry=Number(b.expires);const signature=crypto.createHmac('sha256',process.env.GRADEFLIP_PLUGIN_PASSWORD).update(b.request+'|'+expiry).digest('hex');if(expiry<Date.now()||!b.signature||!crypto.timingSafeEqual(Buffer.from(hash(signature)),Buffer.from(hash(b.signature)))){json(res,400,{error:'Sign-in request expired'});return true;}}
q.scope=q.scope||'research:read research:write';if(!q.scope.split(' ').includes('research:read')||!q.scope.split(' ').includes('research:write')){json(res,400,{error:'Both research scopes required'});return true;}const client=await pool.query('SELECT redirects FROM gradeflip_oauth_clients WHERE id=$1',[q.client_id]);if(!client.rowCount||!client.rows[0].redirects.includes(q.redirect_uri)||q.response_type!=='code'||q.code_challenge_method!=='S256'||! /^[A-Za-z0-9_-]{43}$/.test(q.code_challenge||'')||q.resource!==ORIGIN+'/mcp'||(q.scope||'').split(' ').some(s=>!['research:read','research:write'].includes(s))){json(res,400,{error:'Invalid authorization request'});return true;}
if(req.method==='GET'){const request=u.searchParams.toString(),expires=Date.now()+600000,signature=crypto.createHmac('sha256',process.env.GRADEFLIP_PLUGIN_PASSWORD).update(request+'|'+expires).digest('hex');html(res,`<h1>Connect GradeFlip Research</h1><p>Allow this ChatGPT connection to read and save your card research. Existing Pokemon prices will not be modified.</p><form method="post"><input type="hidden" name="request" value="${safe(request)}"><input type="hidden" name="expires" value="${expires}"><input type="hidden" name="signature" value="${signature}"><label>Connection password <input name="password" type="password" required autocomplete="current-password"></label><button>Connect GradeFlip</button></form>`);return true;}
const code=random();await pool.query('INSERT INTO gradeflip_oauth_codes(code_hash,data,expires) VALUES($1,$2,NOW()+INTERVAL \'5 minutes\')',[hash(code),q]);const redirect=new URL(q.redirect_uri);redirect.searchParams.set('code',code);if(q.state)redirect.searchParams.set('state',q.state);redirect.searchParams.set('iss',ORIGIN);res.writeHead(302,{Location:redirect.href,'Cache-Control':'no-store'});res.end();return true;}
if(p==='/plugin/token'&&req.method==='POST'){const b=await body(req);const row=await pool.query('DELETE FROM gradeflip_oauth_codes WHERE code_hash=$1 AND expires>NOW() RETURNING data',[hash(String(b.code||''))]);const q=row.rows[0]?.data;if(!q||b.grant_type!=='authorization_code'||b.client_id!==q.client_id||b.redirect_uri!==q.redirect_uri||b.resource!==q.resource||! /^[A-Za-z0-9._~-]{43,128}$/.test(b.code_verifier||'')||crypto.createHash('sha256').update(b.code_verifier).digest('base64url')!==q.code_challenge){json(res,400,{error:'invalid_grant'});return true;}json(res,200,{access_token:await token(),token_type:'Bearer',expires_in:2592000,scope:q.scope});return true;}
if(p==='/plugin/login'){res.writeHead(303,{Location:'/research'});res.end();return true;}
if(false){if(req.method==='GET'){html(res,'<h1>GradeFlip Research</h1><form method="post"><label>Connection password <input name="password" type="password" required autocomplete="current-password"></label><button>Open research dashboard</button></form>');return true;}const b=await body(req);if(limited(req)||!passwordOK(b.password)){json(res,401,{error:'Incorrect password or too many attempts'});return true;}const t=await token();res.writeHead(303,{Location:'/research','Set-Cookie':`gradeflip_research=${t}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`,'Cache-Control':'no-store'});res.end();return true;}
if(p==='/api/research'&&req.method==='GET'){json(res,200,await list(Object.fromEntries(u.searchParams)));return true;}
if(!await authorized(req)){res.setHeader('WWW-Authenticate',`Bearer resource_metadata="${ORIGIN}/.well-known/oauth-protected-resource/mcp"`);json(res,401,{error:'Sign in to GradeFlip Research'});return true;}
if(p==='/api/research'&&req.method==='GET'){json(res,200,await list(Object.fromEntries(u.searchParams)));return true;}
if(p==='/mcp'){if(req.method!=='POST'){json(res,405,{error:'Use Streamable HTTP POST'});return true;}const transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true}),s=mcp();res.on('close',()=>{transport.close();s.close();});await s.connect(transport);await transport.handleRequest(req,res,await body(req));return true;}json(res,405,{error:'Method not allowed'});return true;}
return {init,route,save,list,mcp,authorized};}
module.exports={createPlugin,strategy};
